### ISSUE TITLE
 Problems on training the whole network from scratch

### ISSUE THREAD

**Issue by TianChenone** [JustinhoCHN/SRGAN_Wasserstein#11]
When planning to train the whole network from scratch, I face following dilemma:
If I run "python main.py" directly without download g_sran.npz.
The command line will show error information like "failed to load checkpoint/g_sran.npz;failed to load checkpoint/g_sran_init.npz..."
But if I put the g_sran.npz(the pre-trained model original object supplied)in the checkpoint, this error disappears, instead of the error of "ValueError: Dimension 0 in both shapes must be equal, but are 9 and 3 for 'Assign' (op: 'Assign') with input shapes: [9,9,3,64], [3,3,3,64]."
I guess it is caused by the different between variables' number of new model and pre-trained model, but how can I solve it? I run the project on TF1.4.0 and TL1.8.0.
Thank you very much!

**Comment by JustinhoCHN** [comment]
> Start evaluation. (pretrained model for DIV2K) An important note: This pretrained weights is provided by the original author @zsdonghao , his final layer's conv kernel of SRGAN_g (model.py line 53) is using 1×1 kernel, but I changed this kernel to 9×9, so if you use this pretrained weights, you may get the weights unequal error. Two advice: 1)Train the whole network from scratch, you'll get the 9×9 version weights, for further training or evaluating images. 2)You can just change the SRGAN_g 's final conv kernel (model.py line 53) to (1, 1) instead of (9, 9), and change the model.py line 35 conv kernel from (9, 9) to (3, 3), so that you can use the pretrained weights.

Check the note above please, maybe the last line is the solution.

**Comment by TianChenone** [comment]
Thanks!
