### ISSUE TITLE
Why do images do poorly when the resolution is less than 100

### ISSUE THREAD

**Issue by huangqianfirst** [JustinhoCHN/SRGAN_Wasserstein#9]
I am confuse why some test image greater than 300pix can works well, but when i test images which resolution less than 100pix or around 100pixel , the texture detail can't recover while the model it trained by 96*96 to 384*384 . like below , lr is input, 4x_gen is output. I kown it lr images may has been lost many detil, but why result is so awful and how **can i impove upscale result of images resolution around 100pixel.
![sence6_4x_gen_400_748](https://user-images.githubusercontent.com/11473038/44194645-33f2fa80-a169-11e8-99c3-1ce4a8e983fd.png)
![sence6_lr_100_187](https://user-images.githubusercontent.com/11473038/44194646-33f2fa80-a169-11e8-859b-33a203f49027.png)

![3_4x_gen_300_508](https://user-images.githubusercontent.com/11473038/44194317-3143d580-a168-11e8-8c5a-cc7fec93c95b.png)
![3_lr_75_127](https://user-images.githubusercontent.com/11473038/44194318-32750280-a168-11e8-8031-8698f22efd94.png)

**Comment by JustinhoCHN** [comment]
Maybe your test image is jpg format, the compression quality is low, it throws away many information and bringing some artifacts. By the way, we don't have a single model that can super resolve all kinds of LR images for now, especially jpg images. Maybe you have to finetune the model with your own dataset, it may get better result.

**Comment by huangqianfirst** [comment]
thanks. 
----
 Maybe you have to finetune the model with your own dataset, it may get better result.
----
for this, the second image above (the texture of clothing) ,it's come from the same data set with train data and it is a .png format. The reason why the texture of clothing is bad may result from the input lr image is too small to cover too many information for SR. It's also the same with some low resolution or lossy image can't work with SRGAN. So i still have question for how to improve low resolution image quatity, for the model is train for 96*96 to 384*384.
Yes, for the jpg image it also not do good, A lot of noise be introduced.
Do you have some idea to fix jpg image SR result ?

**Comment by JustinhoCHN** [comment]
@huangqianfirst I'm afraid not for now, but there's some paper working on artifacts removal, you can check this out: [Deep Generative Adversarial Compression Artifact Removal](http://arxiv.org/abs/1704.02518)

**Comment by huangqianfirst** [comment]
@JustinhoCHN Thank you

**Comment by JustinhoCHN** [comment]
Recently, one ECCV2018 paper explained why SRGAN would introduce artifacts, just like your images. It is because the BN layers introduced many noise from batch dataset, you can read this paper: [ESRGAN: Enhanced Super-Resolution Generative Adversarial Networks](https://github.com/xinntao/ESRGAN.) @huangqianfirst

**Comment by huangqianfirst** [comment]
Yes, I have been read it. Thanks.@JustinhoCHN .But jepg  images upscale artifacts still exists. I trained  jepg compression artifacts images with hr images , this questions has been quite solved.
